#!/bin/bash
clear

gcc -c server.c 
gcc -c dict.c
gcc -c filestorage.c
gcc -c dirstorage.c

gcc server.o dict.o filestorage.o dirstorage.o -o server -lpthread
#-p port -s save dir -t type save dir/file
#./server -p 8888 
./server -p 8888 -t dir
exit 1
